Critters/Models/Critters.cs
using System.Runtime.Serialization;

namespace Critters.Models;

public class Critters
{
    public List<Roster> Rosters { get; set; }
    
    public List<Temp> Temps { get; set; }
    
    public DeleteConditions Conditions { get; set; }
}

Critters/Models/CrittersModel.cs
namespace Critters.Models;

public class CrittersModel
{
    public List<Roster> Rosters { get; set; }
    public List<Temp> Temps { get; set; }
    public DeleteConditions Conditions { get; set; }
}

Critters/Models/DeleteConditions.cs
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Critters.Models;

public class DeleteConditions
{
    private IEnumerable<SelectListItem> _chosenPosition;
    
    [DataType(DataType.Date)] 
    public DateTime From { get; set; }
    
    [DataType(DataType.Date)] 
    public DateTime To { get; set; }
    
    public string Position { get; set; }
}

Critters/Models/DeleteContract.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace Critters.Models
{
    public class DeleteContract
    {
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Position { get; set; }
        public string AllRosters { get; set; }
        public List<string> CheckboxesRosters  { get; set; }
    }
}

Critters/Models/ErrorViewModel.cs
namespace Critters.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Critters/Models/RecoverContract.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Web;

namespace Critters.Models
{
    public class RecoverContract
    {
        public string AllTemps { get; set; }
        public List<string> CheckboxesTemps { get; set; }
    }
}

Critters/Models/Roster.cs
using System.Runtime.Serialization;

namespace Critters.Models
{
    public class Roster
    {
        public string Playerid { get; set; }
        
        public int? Jersey{ get; set; }
        
        public string Fname{ get; set; }
        
        public string Sname{ get; set; }
        
        public string Position{ get; set; }
        
        public DateTime Birthday{ get; set; }
        
        public int? Weight{ get; set; }
        
        public int? Height{ get; set; }
        
        public string Birthcity{ get; set; }
        
        public string Birthstate{ get; set; }

        public static implicit operator Roster(Temp temp)
        {
            return new Roster()
            {
                Playerid = temp.Playerid,
                Birthcity = temp.Birthcity,
                Birthday = temp.Birthday,
                Birthstate = temp.Birthstate,
                Fname = temp.Fname,
                Height = temp.Height,
                Weight = temp.Weight,
                Jersey = temp.Jersey,
                Position = temp.Position,
                Sname = temp.Sname
            };
        }
    }
}

Critters/Models/RosterView.cs
namespace Critters.Models;

public class RosterView
{
    public List<Roster> Rosters { get; set; }
    
    public List<Temp> Temps { get; set; }
    
    public DeleteConditions Conditions { get; set; }
}

Critters/Models/Temp.cs
namespace Critters.Models
{
    public class Temp
    {
        public string Playerid { get; set; }
        
        public int? Jersey{ get; set; }
        
        public string Fname{ get; set; }
        
        public string Sname{ get; set; }
        
        public string Position{ get; set; }
        
        public DateTime Birthday{ get; set; }
        
        public int? Weight{ get; set; }
        
        public int? Height{ get; set; }
        
        public string Birthcity{ get; set; }
        
        public string Birthstate{ get; set; }

        public static implicit operator Temp(Roster roster)
        {
            return new Temp()
            {
                Playerid = roster.Playerid,
                Birthcity = roster.Birthcity,
                Birthday = roster.Birthday,
                Birthstate = roster.Birthstate,
                Fname = roster.Fname,
                Height = roster.Height,
                Weight = roster.Weight,
                Jersey = roster.Jersey,
                Position = roster.Position,
                Sname = roster.Sname
            };
        }
    }
}

Critters/Controllers/HomeController.cs
using Critters.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Critters.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Critters/Controllers/RosterController.cs
using Critters.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Net;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Text.Json;

namespace Critters.Controllers
{
    public class RosterController : Controller
    {
        private readonly string _serviceURL;
        private readonly List<SelectListItem> _positions;
        public RosterController()
        {
            _serviceURL = "http://localhost:60975/WCFserviceREST.svc";
            _positions = new List<SelectListItem>
            {
                new("RW", "RW"),
                new("D", "D"),
                new("LW", "LW"),
                new("C", "C"),
                new("G", "G")
            };
        }


        [HttpGet]
        public async Task<IActionResult> Players()
        {
            return View(getCritters());
        }


        private RosterView getCritters()
        {
            ViewBag.Positions = _positions;

            using (WebClient proxy = new WebClient())
            {
                DataContractSerializer ser = new DataContractSerializer(typeof(RosterView));
                byte[] data = proxy.DownloadData(_serviceURL + "/GetCritters");
                RosterView model = (ser.ReadObject(new MemoryStream(data)) as RosterView)!;

                return model;
            }
        }

        [HttpPost]
        public async Task<IActionResult> Players(RosterView model, string delete, string recover, string allRosters,
            List<string> checkboxesRosters, string allTemps, List<string> checkboxesTemps)
        {

            if (!string.IsNullOrEmpty(delete))
            {
                DeleteContract contract = new DeleteContract()
                {
                    FromDate = model.Conditions.From,
                    ToDate = model.Conditions.To,
                    Position = model.Conditions.Position ?? "",
                    AllRosters = allRosters ?? "",
                    CheckboxesRosters = checkboxesRosters
                };

                using (WebClient client = new WebClient())
                {
                    client.Headers["Content-type"] = @"application/xml";

                    MemoryStream ms = new MemoryStream();
                    DataContractSerializer ser = new DataContractSerializer(typeof(DeleteContract));
                    ser.WriteObject(ms, contract);
                    client.UploadData(_serviceURL + "/Delete", "DELETE", ms.ToArray());
                }
            }
            else if (!string.IsNullOrEmpty(recover))
            {
                RecoverContract contract = new RecoverContract()
                {
                    AllTemps = allTemps ?? "",
                    CheckboxesTemps = checkboxesTemps
                };

                using (WebClient client = new WebClient())
                {
                    client.Headers["Content-type"] = @"application/xml";

                    MemoryStream ms = new MemoryStream();
                    DataContractSerializer ser = new DataContractSerializer(typeof(RecoverContract));
                    ser.WriteObject(ms, contract);
                    client.UploadData(_serviceURL + "/Recover", "PUT", ms.ToArray());
                }

            }

            return View(getCritters());
        }



    }
}

Critters/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Critters/Views/Roster/Players.cshtml
@using Microsoft.AspNetCore.Mvc.Rendering
@model CrittersModel

<script language="JavaScript">
    function toggle(source, name) {
        var checkboxes = document.getElementsByName(name);
        for (var i = 0; i < checkboxes.length; i++) {
            checkboxes[i].checked = source.checked;
        }
    }

    function toggle_unit(source, name) {
        var checkbox = document.getElementsByName(name)[0];
        if (!source.checked && checkbox.checked) {
            checkbox.checked = false;
        }
        
    }
</script> 


        @using (Html.BeginForm("Players", "Roster", FormMethod.Post))
                    {
    

        <div class="row">
            <div class="col">
                <div class="row" style="margin-bottom: 10px; margin-top: 10px; align-content: center; align-items: center">
                    <div class="col">
                        <label>From</label> @Html.EditorFor(p => p.Conditions.From, new Dictionary<string, object>{{"class", "form-control"}})
                    </div>
                    
                    <div class="col">
                        <label>to</label> @Html.EditorFor(p => p.Conditions.To)
                    </div>
                    
                    <div class="col">
                        @Html.DropDownListFor(p => p.Conditions.Position, ViewBag.Positions as List<SelectListItem>, "Position", new {style="width: 100px"})
                        @* <label>Position</label> @Html.EditorFor(p => p.Conditions.Position) *@
                    </div>
                    <div class="col">
                        <input class="btn btn-danger" type="submit" value="Delete" name="delete"/>
                    </div>
                </div>
                <table class="table">
                    <thead style="background-color: green">
                    <tr>
                        <th scope="col">
                            <input type="checkbox" name="allRosters" value="allRosters" onclick="toggle(this, 'checkboxesRosters')"/>
                        </th>
                        <th scope="col">Player Id</th>
                        <th scope="col">Jersey</th>
                        <th scope="col">First name</th>
                        <th scope="col">Second name</th>
                        <th scope="col">Position</th>
                        <th scope="col">Birthday</th>
                        <th scope="col">Weight</th>
                        <th scope="col">Height</th>
                        <th scope="col">Birth city</th>
                        <th scope="col">Birth state</th>
                    </tr>
                    </thead>
                    <tbody>
                    @{
                        foreach (Roster roster in Model.Rosters)
                        {
                            <tr>
                                <td> <input class="checkbox" name="checkboxesRosters" value=@roster.Playerid type="checkbox" onclick="toggle_unit(this, 'allRosters')"/></td>
                                <td scope="col">@roster.Playerid</td>
                                <td scope="col">@roster.Jersey?.ToString()</td>
                                <td scope="col">@roster.Fname</td>
                                <td scope="col">@roster.Sname</td>
                                <td scope="col">@roster.Position</td>
                                <td scope="col">@roster.Birthday.ToLongDateString()</td>
                                <td scope="col">@roster.Weight?.ToString()</td>
                                <td scope="col">@roster.Height?.ToString()</td>
                                <td scope="col">@roster.Birthcity</td>
                                <td scope="col">@roster.Birthstate</td>
                            </tr>
                        }
                    }
                    </tbody>
                </table>
            </div>
    @* <div class="col-md-4"></div> *@
    <div class="col">
        <div class="row" style="margin-bottom: 10px; margin-top: 10px; text-align: center">
            <div class="col">
                <input type="submit" class="btn btn-success" value="Recover" name="recover"/>
            </div>
        </div>
        <table class="table">
            <thead style="background-color: red">
            <tr>
                <th scope="col">
                    <input type="checkbox" name="allTemps" value="allTemps" onclick="toggle(this, 'checkboxesTemps')"/>
                </th>
                <th scope="col">Player Id</th>
                <th scope="col">Jersey</th>
                <th scope="col">First name</th>
                <th scope="col">Second name</th>
                <th scope="col">Position</th>
                <th scope="col">Birthday</th>
                <th scope="col">Weight</th>
                <th scope="col">Height</th>
                <th scope="col">Birth city</th>
                <th scope="col">Birth state</th>
            </tr>
            </thead>
            <tbody>
            @{
                foreach (Temp temp in Model.Temps)
                {
                    <tr>
                        <td> <input class="checkbox" name="checkboxesTemps" value=@temp.Playerid type="checkbox" onclick="toggle_unit(this, 'allTemps')"/></td>
                        <td scope="col">@temp.Playerid</td>
                        <td scope="col">@temp.Jersey?.ToString()</td>
                        <td scope="col">@temp.Fname</td>
                        <td scope="col">@temp.Sname</td>
                        <td scope="col">@temp.Position</td>
                        <td scope="col">@temp.Birthday.ToLongDateString()</td>
                        <td scope="col">@temp.Weight?.ToString()</td>
                        <td scope="col">@temp.Height?.ToString()</td>
                        <td scope="col">@temp.Birthcity</td>
                        <td scope="col">@temp.Birthstate</td>
                    </tr>
                }
            }
            </tbody>
        </table>
    </div>
    </div>
    }

Critters/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Critters</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Critters.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Roster" asp-action="Players">Critters</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
            @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Critters - <a asp-area="" asp-controller="Home" asp-action="Privacy">Secret page</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>